# Generated by Django 4.2.2 on 2023-06-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=887415292959, editable=False, primary_key=True, serialize=False),
        ),
    ]
