# Generated by Django 4.2.2 on 2023-06-18 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_candidacy_user_role_group_candidacy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user'),
        ),
        migrations.AlterField(
            model_name='group',
            name='candidacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.candidacy'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user'),
        ),
    ]
