# Generated by Django 4.2.2 on 2023-06-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_candidacy_user_alter_group_candidacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default=2, max_length=20),
        ),
    ]
