# Generated by Django 4.2.2 on 2023-06-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_candidate_remove_candidacy_user_remove_user_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidacy',
            old_name='description',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='candidacy',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='candidacy',
            old_name='salary_max',
            new_name='salary_exp',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='candidacy',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
